# Generated by Django 2.0.4 on 2018-04-11 12:09

from django.db import migrations


class Migration(migrations.Migration):
    """A data migration to create initial week days for the system
    """

    def create_week_days(apps, schema_editor):
        WeekDay = apps.get_model('connor', 'WeekDay')

        for i in range(1, 8):
            week_day = WeekDay.objects.create(day=i)

            print('\nCreated initial WeekDay for the system: {0}'.format(
                week_day.get_day_display()
            ))

    def remove_week_days(apps, schema_editor):
        pass

    dependencies = [
        ('connor', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_week_days,
            remove_week_days
        ),
    ]
