# Generated by Django 2.0.4 on 2018-04-12 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connor', '0003_auto_20180411_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexcercise',
            name='workout_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connor.WorkoutPlan'),
        ),
    ]
