# Generated by Django 2.0.4 on 2018-04-12 17:56

from django.contrib.auth.models import User
from django.db import migrations


class Migration(migrations.Migration):
    """A data migration to create initial Users for the system
    """

    def create_initial_users(apps, schema_editor):

        # Create users:
        jd = User.objects.create_user(
            username='john_doe',
            first_name='John',
            last_name='Doe',
            email='john_doe@example.com',
        )
        ld = User.objects.create_user(
            username='linda_doe',
            first_name='Linda',
            last_name='Doe',
            email='linda_doe@example.com',
        )
        md = User.objects.create_user(
            username='matthew_doe',
            first_name='Matthew',
            last_name='Doe',
            email='matthew_doe@example.com',
        )

        # set passwords:
        jd.set_password('test')
        ld.set_password('test')
        md.set_password('test')

        jd.save()
        ld.save()
        md.save()

        for user in [jd, ld, md]:
            print('\nCreated initial user: {0}'.format(user.get_full_name()))

    def remove_initial_users(apps, schema_editor):
        pass

    dependencies = [
        ('connor', '0004_workoutexcercise_workout_plan'),
    ]

    operations = [
        migrations.RunPython(
            create_initial_users,
            remove_initial_users
        ),
    ]
