# Generated by Django 2.0.4 on 2018-04-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connor', '0009_assign_exercises'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutexcercise',
            name='workout_plan',
        ),
        migrations.AddField(
            model_name='workoutexcercise',
            name='workout_plan',
            field=models.ManyToManyField(to='connor.WorkoutPlan'),
        ),
    ]
