# Generated by Django 2.0.4 on 2018-04-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connor', '0011_reassign_exercises_to_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutexcercise',
            name='days',
            field=models.ManyToManyField(blank=True, related_name='workout_exercises', to='connor.WeekDay'),
        ),
        migrations.AlterField(
            model_name='workoutexcercise',
            name='workout_plan',
            field=models.ManyToManyField(related_name='workout_exercises', to='connor.WorkoutPlan'),
        ),
    ]
