# Generated by Django 2.0.4 on 2018-04-13 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connor', '0012_auto_20180413_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutexcercise',
            old_name='workout_plan',
            new_name='workout_plans',
        ),
    ]
