# Generated by Django 2.0.4 on 2018-04-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connor', '0013_auto_20180413_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekday',
            name='day',
            field=models.PositiveIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='workoutexcercise',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
