# Generated by Django 2.0.4 on 2018-04-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connor', '0014_auto_20180413_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutplan',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
